# Generated by Django 5.1 on 2024-08-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('isMale', models.BooleanField(null=True)),
                ('year', models.IntegerField(default=0)),
                ('sports', models.TextField()),
            ],
        ),
    ]
