# Generated by Django 5.1 on 2024-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlympicMedal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='isFemale',
            field=models.BooleanField(null=True),
        ),
    ]
