# Generated by Django 5.1 on 2024-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlympicMedal', '0002_data_isfemale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sports',
            field=models.TextField(default='All'),
        ),
    ]
