# Generated by Django 5.1 on 2024-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlympicMedal', '0004_alter_data_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sports',
            field=models.TextField(null=True),
        ),
    ]
