# Generated by Django 5.1 on 2024-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlympicMedal', '0005_alter_data_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='medal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='season',
            field=models.TextField(null=True),
        ),
    ]
